services:
  ia_pyinstaller:
    hostname:         ia_pyinstaller.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_pyinstaller:latest
    #    -           ia_pyinstaller:latest
    #    - innovanon/ia_pyinstaller
    #    -           ia_pyinstaller
    image:            innovanon/ia_pyinstaller
    restart:          no
    logging:
      driver:         syslog   
